### ISSUE TITLE
Site DNS and SSL certs

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/Slingshot#10]
We need to purchase ssl certs for rockrms.church (or possibly get the free ssl certs? Isn't there a way to do that now @johnthepink?) 

We also need to add a DNS entry for rockrms.church to go to `54.164.169.239`

Once certs are obtained, we need to create a `bundle.crt` and a `private.key` per docs found [here](https://github.com/meteorhacks/mup-frontend-server). Then they should be added to [ops-settings](https://github.com/NewSpring/ops-settings) under the sites/rockrms.church folder

_Note_
After certs are added, `mupx setup` will need to be run from the project on circle. After adjusting the circle file to include copying certs, ssh in and run `mupx setup`. Then deploys can go on as normal

**Comment by JayGreentree-Codes** [comment]
Check out https://www.freessl.com/ its available from RapidSSL

**Comment by jbaxleyiii** [comment]
Story points: 3

**Comment by johnthepink** [comment]
@jbaxleyiii @JayGreentree this is what i have been looking at for free SSL https://letsencrypt.org/

**Comment by delianides** [comment]
@jbaxleyiii If we are managing installs with subdomains and want those to be secured too, then we'll have to buy a cert. I don't know if any place offering free wildcard certs. @JayGreentree freessl is only for 30 days.

**Comment by jbaxleyiii** [comment]
@delianides sounds good, a wildcard cert it is

**Comment by johnthepink** [comment]
@delianides @jbaxleyiii let me do a little research on the subdomain generation before we buy a wildcard cert. i don't anticipate it being a great undertaking, but just in case it won't be finished this week.

**Comment by JayGreentree-Codes** [comment]
@johnthepink Yup sorry I realized later after posting it was only 30 days Also the Lets encrypt site is only 90 days in case you didn't see the post.
See https://letsencrypt.org/2015/11/12/public-beta-timing.html for details.

**Comment by jbaxleyiii** [comment]
done!
