### ISSUE TITLE
Docs: Importing a SQL db to Azure

### ISSUE THREAD

**Issue by dcs619** [NewSpring/Slingshot#21]
# Importing an existing SQL Database

First thing you'll need to do is create a .BACPAC file from your existing database.  Azure Cloud can't or doesn't support the existing .BAK structure.

Right-click the database, export Data-Tier Application:

![image](https://cloud.githubusercontent.com/assets/1210933/11194017/c3fe3e3c-8c77-11e5-9003-ea873ebcc6f0.png)

Next, you'll need to connect to the Azure instance you set up.  Right-click the connection and select Import Data-Tier Application:

![image](https://cloud.githubusercontent.com/assets/1210933/11194250/067d1d54-8c79-11e5-90e1-592e220f6461.png)

Select the .BACPAC you created in step 1 and follow the steps.  If you get an error during the upload, there may be security limitations on the account (especially the Free Trial). 

Alternatively, you can upload the .BACPAC to your cloud storage and restore to a new database instance.  _You'll need to add storage if you haven't already done so_.  You can upload over the command line or using a [GUI tool](https://azurestorageexplorer.codeplex.com/releases/).

Select the storage provider, plan and login credentials you used to set up the SQL instance:

![image](https://cloud.githubusercontent.com/assets/1210933/11194354/938c1b3c-8c79-11e5-95aa-b2e4e882f483.png)

Provisioning will take a few minutes, you can just wait or open monitoring on the instance: 

![image](https://cloud.githubusercontent.com/assets/1210933/11194416/f00def7a-8c79-11e5-89cb-be9634db5490.png)
#### Dependencies:
- Powershell
- SQL Management Studio 12+ (for exports)
#### More info:

https://azure.microsoft.com/en-us/documentation/articles/sql-database-import/

http://blogs.technet.com/b/cbernier/archive/2013/09/11/move-your-sql-server-databases-to-windows-azure-sql.aspx
# Creating a new SQL database from migrations

Not yet sure how this is done.
#### Dependencies:
- Powershell
- Nuget Package Manager
#### More info:

https://coding.abel.nu/2012/03/ef-migrations-command-reference/#Update-Database

http://stackoverflow.com/questions/17020393/asp-net-mvc-4-migrations-how-to-run-update-database-on-a-production-server/17024918#17024918

**Comment by dcs619** [comment]
@johnthepink @delianides Let me know how this can be more helpful; hopefully the terminology makes sense when setting up SQL instances.

**Comment by johnthepink** [comment]
@dcs619 seems pretty straight foward to me

**Comment by dcs619** [comment]
This is no longer the recommended process to set up a Rock db on Azure. Closing
