### ISSUE TITLE
Set up webpack application structure

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/Slingshot#5]
- [x] set up meteor app
- [x] add some documentation for getting started

**Comment by jbaxleyiii** [comment]
@johnthepink if you could add some how to build the app / how to structure that would be great!

**Comment by jbaxleyiii** [comment]
Story points: 3

**Comment by johnthepink** [comment]
@jbaxleyiii will do

**Comment by johnthepink** [comment]
Closed via #19
