### ISSUE TITLE
[MVP] Create mobile nav

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/Slingshot#54]

**Comment by briankalwat** [comment]
@jbaxleyiii I got some of this converted to how the footer is done, but I couldn't figure out how to only add `soft-sides` to the link if it didn't have a btnClass defined. I tried checking to see if it was undefined and pushing `soft-sides` to another classes array, but I couldn't get it to work.

https://github.com/NewSpring/Slingshot/blob/feature-navigation/modules/slingshot/client/sections/navbar.jsx#L12
