### ISSUE TITLE
subdomain generation

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/Slingshot#9]
- [x] research
- [x] working example
- [x] integrate

**Comment by jbaxleyiii** [comment]
Story points: 13

**Comment by johnthepink** [comment]
We should be able to do this using the [Azure DNS API](https://msdn.microsoft.com/en-us/library/azure/mt130640.aspx). I need to read some more about it.

**Comment by jbaxleyiii** [comment]
@johnthepink that would be great, as much as possible keeping things with Azure is a win. Easier to hand off as well.
